version: '3'
services:
  my-blog-admin-ui:
    build:
      context: .
    restart: always
    container_name: my-blog-admin-ui
    image: my-blog-admin-ui
    networks:
      - spring_cloud_default
    external_links:
      - my-blog-admin-gateway
    ports:
      - 80:80

# 加入到后端网络， 默认为 spring_cloud_default  | docker network ls   查看
networks:
  spring_cloud_default:
    external: true
